#Projeto Rivendel Criação e Instalação do Zabbix Server com Ansible

- name: Rivendel Tecnologia Projeto Ansible + Instalação do Zabbix Server
  hosts: ec2
  become: true

  roles:
    - apache
    - php
    - mariadb
    - zabbix
