#Projeto Rivendel Criação e Instalação do Zabbix Server com Ansible

- name: Rivendel Tecnologia Projeto Ansible + Vagrant Instalação do Zabbix Server
  hosts: all
  user: vagrant
  become: yes

  roles:
    - apache
    - mysql
    - php
    - zabbix
