# Task para instalar os pacotes do PHP

     - name: Instalar os pacotes do PHP
       action: yum pkg={{item}} state=installed
       with_items:
         - php
         - php-cli
         - php-common
         - php-devel
         - php-pear
         - php-gd
         - php-mbstring
         - php-mysql
         - php-xml
